openapi: 3.0.3
info:
  contact:
    email: support@salestim.com
    name: SalesTim Support
    url: https://developers.salestim.com/api
  description: |
    The Microsoft Teams Governance API
  license:
    name: (c) Copyright 2019-2020 SalesTim - all rights reserved.
    url: https://www.salestim.com/legal/eula
  termsOfService: https://www.salestim.com/legal/tos
  title: SalesTim API
  version: 1.0.0
servers:
- description: SalesTim API v1.0 (Production environment, uses live data)
  url: https://api.salestim.io/v1.0
tags:
- description: Microsoft Teams and policy templates from the public template store
  externalDocs:
    url: https://developers.salestim.com/api/reference/Apis/StoreApi
  name: Store
- description: Microsoft Teams and policy templates from your corporate catalog
  externalDocs:
    url: https://developers.salestim.com/api/reference/Apis/CatalogApi
  name: Catalog
- description: SalesTim Virtual Apps that may access this API
  externalDocs:
    url: https://developers.salestim.com/api/reference/resources/AppsApi
  name: Apps
- description: Governance jobs that performs governance operations
  externalDocs:
    url: https://developers.salestim.com/api/reference/Apis/JobsApi
  name: Jobs
paths:
  /store/templates:
    get:
      description: View all templates from the public [Template Store](https://store.salestim.com)
        or publish your own templates to the [Template Manifests Repository](https://github.com/SalesTim/template-manifests)
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/StoreApi.html#getstoretemplates
      operationId: GetStoreTemplates
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfStoreTemplates'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      summary: Get all templates from the public template store
      tags:
      - Store
      x-eov-operation-handler: controllers/StoreController
  /store/templates/{id}:
    get:
      description: View all templates from the public [Template Store](https://store.salestim.com)
        or publish your own templates to the [Template Manifests Repository](https://github.com/SalesTim/template-manifests)
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/StoreApi.html#getstoretemplate
      operationId: GetStoreTemplate
      parameters:
      - description: The template ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreTemplate'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      summary: Get a store template
      tags:
      - Store
      x-eov-operation-handler: controllers/StoreController
  /store/templates/byCategory/{id}:
    get:
      description: View all templates from the public [Template Store](https://store.salestim.com)
        or publish your own templates to the [Template Manifests Repository](https://github.com/SalesTim/template-manifests)
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/StoreApi.html#getstoretemplatesbycategory
      operationId: GetStoreTemplatesByCategory
      parameters:
      - description: The category ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfStoreTemplates'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      summary: Get store template from a specific category
      tags:
      - Store
      x-eov-operation-handler: controllers/StoreController
  /store/categories:
    get:
      description: View all templates from the public [Template Store](https://store.salestim.com)
        or publish your own templates to the [Template Manifests Repository](https://github.com/SalesTim/template-manifests)
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/StoreApi.html#getstorecategories
      operationId: GetStoreCategories
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfStoreCategories'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      summary: Get all store categories from the public template store
      tags:
      - Store
      x-eov-operation-handler: controllers/StoreController
  /catalog/templates:
    get:
      description: Get all templates from your corporate catalog
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/CatalogApi.html#getcatalogtemplates
      operationId: GetCatalogTemplates
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCatalogTemplates'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      - appId: []
        appSecret: []
      summary: Get all templates from your corporate catalog
      tags:
      - Catalog
      x-eov-operation-handler: controllers/CatalogController
  /catalog/templates/installFromStore:
    post:
      description: Install a template from the public template store to your corporate
        catalog
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/CatalogApi.html#installtemplatefromstore
      operationId: InstallTemplateFromStore
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateIdentifier'
        description: The template to be installed
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogTemplate'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      summary: Install a template from the public template store to your corporate
        catalog
      tags:
      - Catalog
      x-eov-operation-handler: controllers/CatalogController
  /apps:
    get:
      description: Get all virtual apps in a tenant
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/AppsApi.html#getapps
      operationId: GetApps
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfApps'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      summary: Get all virtual apps in a tenant
      tags:
      - Apps
      x-eov-operation-handler: controllers/AppsController
    post:
      description: Create a new virtual app and get its generated ID and secret.
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/AppsApi.html#createapp
      operationId: CreateApp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
        description: List of properties to be updated.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      summary: Create a virtual app
      tags:
      - Apps
      x-eov-operation-handler: controllers/AppsController
  /apps/{id}/regenerateSecret:
    post:
      description: Regenerate a virtual app secret
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/AppsApi.html#regenerateappsecret
      operationId: RegenerateAppSecret
      parameters:
      - description: The virtual app ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      summary: Regenerate a virtual app secret
      tags:
      - Apps
      x-eov-operation-handler: controllers/AppsController
  /apps/{id}:
    delete:
      description: Delete a virtual app
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/AppsApi.html#deleteApp
      operationId: DeleteApp
      parameters:
      - description: ID of the virtual app to delete
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      summary: Delete a virtual app
      tags:
      - Apps
      x-eov-operation-handler: controllers/AppsController
    put:
      description: Update a virtual app
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/AppsApi.html#updateApp
      operationId: UpdateApp
      parameters:
      - description: ID of the virtual app to update
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
        description: List of properties to be updated.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - bearerAuth: []
      summary: Update a virtual app
      tags:
      - Apps
      x-eov-operation-handler: controllers/AppsController
  /jobs/{id}:
    get:
      description: Get detailed information about a job (Status, logs...)
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/JobsApi.html#getjob
      operationId: GetJob
      parameters:
      - description: The job ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - appId: []
        appSecret: []
      summary: Get detailed information about a job (Status, logs...)
      tags:
      - Jobs
      x-eov-operation-handler: controllers/JobsController
  /jobs/provisioning:
    post:
      description: Create a new provisioning job by sending a ProvisioningRequest
      externalDocs:
        url: https://developers.salestim.com/api/reference/Apis/JobsApi.html#createprovisioningjob
      operationId: CreateProvisioningJob
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisioningRequest'
        description: A ProvisioningRequest object describing the job to execute
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: Operation executed successfully.
        "401":
          description: API key or app id are missing or invalid.
        "404":
          description: The ressource cannot be found.
        "429":
          description: Too many requests. Your request has been throttled.
        "500":
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
        "503":
          description: Service unavailable.
        default:
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - appId: []
        appSecret: []
      summary: Create a new provisioning job by sending a ProvisioningRequest
      tags:
      - Jobs
      x-eov-operation-handler: controllers/JobsController
components:
  responses:
    Success:
      description: Operation executed successfully.
    UnauthorizedError:
      description: API key or app id are missing or invalid.
    NotFoundError:
      description: The ressource cannot be found.
    TooManyRequests:
      description: Too many requests. Your request has been throttled.
    InternalServerError:
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request.
    ServiceUnavailable:
      description: Service unavailable.
  schemas:
    ArrayOfStoreTemplates:
      description: A list of templates from the public template store
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/StoreTemplate.html
      items:
        $ref: '#/components/schemas/StoreTemplate'
      type: array
    StoreTemplate:
      description: A template from the public template store
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/StoreTemplate.html
      type: object
    ArrayOfStoreCategories:
      description: A list of categories from the public template store
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/StoreCategory.html
      items:
        $ref: '#/components/schemas/StoreCategory'
      type: array
    StoreCategory:
      description: A category of templates from the public template store
      example:
        id: id
        label:
          en-us: en-us
          fr-fr: fr-fr
        slug: slug
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/StoreCategory.html
      properties:
        id:
          description: Category ID
          type: string
        label:
          $ref: '#/components/schemas/StoreCategory_label'
        slug:
          description: Category slug used for clean and seo-friendly urls
          type: string
    ArrayOfCatalogTemplates:
      description: A list of templates from your corporate catalog
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/CatalogTemplate.html
      items:
        $ref: '#/components/schemas/CatalogTemplate'
      type: array
    CatalogTemplate:
      description: A template from your corporate catalog
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/CatalogTemplate.html
      type: object
    TemplateIdentifier:
      description: Object defining the ID of a template
      example:
        id: id
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/TemplateIdentifier.html
      properties:
        id:
          description: A template ID
          type: string
      type: object
    ArrayOfApps:
      description: A list of SalesTim virtual apps
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/App.html
      items:
        $ref: '#/components/schemas/App'
      type: array
    App:
      description: A SalesTim virtual app
      example:
        templateConfiguration:
          createdAt: 2000-01-23T04:56:07.000+00:00
          createdBy: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          description: description
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          secret: secret
          enabled: true
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/App.html
      properties:
        templateConfiguration:
          $ref: '#/components/schemas/App_templateConfiguration'
    Job:
      description: A job that performs some tasks asynchronously
      example:
        data: '{}'
        log:
        - log
        - log
        progress: 8
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: type
        status: active
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/Job
      properties:
        id:
          description: The job ID, auto-generated at creation
          format: uuid
          type: string
        log:
          description: The job audit log
          items:
            type: string
          type: array
        type:
          description: The job type (for instance `ProvisioningRequest`)
          type: string
        status:
          description: The job current status
          enum:
          - active
          - waiting
          - completed
          - failed
          - deleyed
          - paused
          - unknownFutureValue
          type: string
        progress:
          description: The job current progress
          maximum: 100
          minimum: 0
          type: integer
        data:
          description: The job data (for instance a `ProvisioningRequest` object)
          type: object
    ProvisioningRequest:
      description: A request to provision a team based on a template from your corporate
        catalog
      example:
        requestedOwners:
        - upn: upn
          id: id
          email: email
        - upn: upn
          id: id
          email: email
        requestedTeamName: requestedTeamName
        requestedTeamDescription: requestedTeamDescription
        onBehalfOfRequester:
          upn: upn
          id: id
          email: email
        requestedTeamWelcomeMessage: requestedTeamWelcomeMessage
        templateId: templateId
        requestedMembers:
        - upn: upn
          id: id
          email: email
        - upn: upn
          id: id
          email: email
      externalDocs:
        url: https://developers.salestim.com/api/reference/Models/ProvisioningRequest
      properties:
        templateId:
          description: The template ID
          type: string
        requestedTeamName:
          description: Requested team name
          type: string
        requestedTeamDescription:
          description: Requested team description
          type: string
        requestedTeamWelcomeMessage:
          description: Requested team welcome message
          type: string
        requestedMembers:
          description: Requested members as an array of objects
          items:
            $ref: '#/components/schemas/ProvisioningRequest_requestedMembers'
          type: array
        requestedOwners:
          description: Requested owners as an array of users. User identifier could
            be its ID, UPN or email.
          items:
            $ref: '#/components/schemas/ProvisioningRequest_requestedMembers'
          type: array
        onBehalfOfRequester:
          $ref: '#/components/schemas/ProvisioningRequest_onBehalfOfRequester'
      required:
      - requestedTeamName
      - templateId
    StoreCategory_label:
      description: Collection of localized category labels
      example:
        en-us: en-us
        fr-fr: fr-fr
      properties:
        en-us:
          description: Category label localized for en-us.
          type: string
        fr-fr:
          description: Category label localized for fr-fr.
          type: string
    App_templateConfiguration:
      description: Main template properties
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        createdBy: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        secret: secret
        enabled: true
      properties:
        name:
          description: The virtual app name
          maxLength: 256
          minLength: 3
          type: string
        description:
          description: The virtual app description
          maxLength: 1024
          minLength: 0
          type: string
        createdBy:
          description: The ID (Fron Azure AD) of the user that created the virtual
            app
          format: uuid
          type: string
        createdAt:
          description: The date of creation of the virtual app
          format: date-time
          type: string
        id:
          description: The virtual app ID, auto-generated at creation
          format: uuid
          type: string
        secret:
          description: |
            The virtual app secret, auto-generated at creation. It may also be regenerated later. Be careful, this property is only available at creation or after an explicit regeneration.
          format: password
          type: string
        enabled:
          default: true
          description: The virtual app status, enabled or disabled
          type: boolean
    ProvisioningRequest_requestedMembers:
      example:
        upn: upn
        id: id
        email: email
      properties:
        id:
          description: User ID
          type: string
        upn:
          description: User UPN
          type: string
        email:
          description: User email
          type: string
    ProvisioningRequest_onBehalfOfRequester:
      description: When creating a new request in `application mode`, indicates that
        the request should be executed on behalf of a specific user. User identifier
        could be its ID, UPN or email. This property is ignored in `delegated mode`.
      example:
        upn: upn
        id: id
        email: email
      properties:
        id:
          description: User ID
          type: string
        upn:
          description: User UPN
          type: string
        email:
          description: User email
          type: string
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: A valid Microsoft 365 access_token issued by Azure AD
      scheme: bearer
      type: http
    appId:
      description: A valid virtual app ID
      in: header
      name: X-APP-ID
      type: apiKey
    appSecret:
      description: A valid virtual app secret
      in: header
      name: X-API-KEY
      type: apiKey
